use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
};

const RESOURCE_ROOT: &str = "assets/resources";

/// Loads validated properties resources and writes their strongly typed Rust representation.
fn main() {
    println!("cargo:rerun-if-changed={RESOURCE_ROOT}");
    let root = Path::new(RESOURCE_ROOT);
    let default_strings = read_properties(&root.join("values/strings.properties"));
    let chinese_strings = read_properties(&root.join("values-zh/strings.properties"));
    let colors = read_properties(&root.join("values/colors.properties"));
    let dimensions = read_properties(&root.join("values/dimensions.properties"));
    let images = read_properties(&root.join("values/images.properties"));

    validate_localized_keys(
        &default_strings,
        &chinese_strings,
        "values-zh/strings.properties",
    );

    let generated = generate_resources(
        &default_strings,
        &chinese_strings,
        &colors,
        &dimensions,
        &images,
        root,
    );
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo must define OUT_DIR"))
        .join("resources_generated.rs");
    fs::write(output, generated).expect("generated resources must be writable");
}

/// Parses a UTF-8 properties file with strict duplicate-key and identifier validation.
fn read_properties(path: &Path) -> BTreeMap<String, String> {
    let source = fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    let mut values = BTreeMap::new();

    for (index, raw_line) in source.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('!') {
            continue;
        }
        let (key, value) = line.split_once('=').unwrap_or_else(|| {
            panic!(
                "{}:{} must use key=value properties syntax",
                path.display(),
                index + 1
            )
        });
        let key = key.trim();
        validate_key(path, index + 1, key);
        if values
            .insert(key.to_owned(), value.trim().to_owned())
            .is_some()
        {
            panic!(
                "{}:{} duplicates resource key `{key}`",
                path.display(),
                index + 1
            );
        }
    }
    values
}

/// Ensures a resource key can be emitted unchanged as a lowercase Rust identifier.
fn validate_key(path: &Path, line: usize, key: &str) {
    let mut characters = key.chars();
    let valid_start = characters
        .next()
        .is_some_and(|character| character.is_ascii_lowercase());
    let valid_rest = characters.all(|character| {
        character.is_ascii_lowercase() || character.is_ascii_digit() || character == '_'
    });
    if !valid_start || !valid_rest || key.ends_with('_') || key.contains("__") {
        panic!(
            "{}:{line} resource key `{key}` must match [a-z][a-z0-9_]* without repeated or trailing underscores",
            path.display()
        );
    }
}

/// Rejects localized keys that do not exist in the complete default language file.
fn validate_localized_keys(
    defaults: &BTreeMap<String, String>,
    localized: &BTreeMap<String, String>,
    source: &str,
) {
    for (key, value) in localized {
        let default = defaults
            .get(key)
            .unwrap_or_else(|| panic!("{source} contains unknown default-language key `{key}`"));
        if placeholders(default) != placeholders(value) {
            panic!("{source} key `{key}` must use the same placeholders as the default language");
        }
    }
}

/// Generates resource enums, resolvers, and literal-key macro arms from validated inputs.
fn generate_resources(
    default_strings: &BTreeMap<String, String>,
    chinese_strings: &BTreeMap<String, String>,
    colors: &BTreeMap<String, String>,
    dimensions: &BTreeMap<String, String>,
    images: &BTreeMap<String, String>,
    resource_root: &Path,
) -> String {
    let mut output =
        String::from("// @generated by build.rs from assets/resources. Do not edit.\n\n");
    generate_text_resources(&mut output, default_strings, chinese_strings);
    generate_color_resources(&mut output, colors);
    generate_dimension_resources(&mut output, dimensions);
    generate_image_resources(&mut output, images, resource_root);
    output
}

/// Generates localized text keys, fallback-aware templates, and parameter-aware macro arms.
fn generate_text_resources(
    output: &mut String,
    defaults: &BTreeMap<String, String>,
    chinese: &BTreeMap<String, String>,
) {
    generate_key_enum(output, "TextKey", defaults.keys());
    output.push_str("\n/// Returns the localized template for a generated text key.\n");
    output.push_str("pub(crate) fn generated_text_template(locale: Locale, key: TextKey) -> &'static str {\n    match (locale, key) {\n");
    for (key, value) in chinese {
        output.push_str(&format!(
            "        (Locale::SimplifiedChinese, TextKey::{key}) => {},\n",
            rust_string(value)
        ));
    }
    for (key, value) in defaults {
        output.push_str(&format!(
            "        (_, TextKey::{key}) => {},\n",
            rust_string(value)
        ));
    }
    output.push_str("    }\n}\n\n");

    output.push_str("macro_rules! text {\n");
    for (key, value) in defaults {
        let placeholders = placeholders(value);
        if placeholders.is_empty() {
            output.push_str(&format!(
                "    ({key}) => {{ __resource_context!().text(crate::resources::TextKey::{key}, &[]) }};\n"
            ));
        } else {
            let parameters = placeholders
                .iter()
                .map(|name| format!("${name}:expr"))
                .collect::<Vec<_>>()
                .join(", ");
            let arguments = placeholders
                .iter()
                .map(|name| format!("({}, ::std::format!(\"{{}}\", ${name}))", rust_string(name)))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "    ({key}, {parameters}) => {{ __resource_context!().text(crate::resources::TextKey::{key}, &[{arguments}]) }};\n"
            ));
        }
    }
    output.push_str("}\n\n");
}

/// Generates semantic color keys and validated RGBA resolver branches.
fn generate_color_resources(output: &mut String, colors: &BTreeMap<String, String>) {
    generate_key_enum(output, "ColorKey", colors.keys());
    output.push_str("\n/// Returns the RGBA channels for a generated semantic color key.\n");
    output
        .push_str("pub(crate) fn generated_color(key: ColorKey) -> [f32; 4] {\n    match key {\n");
    for (key, value) in colors {
        let [red, green, blue, alpha] = parse_color(key, value);
        output.push_str(&format!(
            "        ColorKey::{key} => [{red:?}, {green:?}, {blue:?}, {alpha:?}],\n"
        ));
    }
    output.push_str("    }\n}\n\nmacro_rules! color {\n");
    for key in colors.keys() {
        output.push_str(&format!(
            "    ({key}) => {{ __resource_context!().color(crate::resources::ColorKey::{key}) }};\n"
        ));
    }
    output.push_str("}\n\n");
}

/// Generates dimension keys with explicit layout or text scale classification.
fn generate_dimension_resources(output: &mut String, dimensions: &BTreeMap<String, String>) {
    generate_key_enum(output, "DimensionKey", dimensions.keys());
    output.push_str("\n/// Returns the base value and scale kind for a generated dimension key.\n");
    output.push_str("pub(crate) fn generated_dimension(key: DimensionKey) -> (f32, DimensionScale) {\n    match key {\n");
    for (key, value) in dimensions {
        let (scale, number) = value
            .split_once(':')
            .unwrap_or_else(|| panic!("dimension `{key}` must use layout:number or text:number"));
        let number: f32 = number
            .parse()
            .unwrap_or_else(|_| panic!("dimension `{key}` contains invalid number `{number}`"));
        if !number.is_finite() || number < 0.0 {
            panic!("dimension `{key}` must be a finite non-negative number");
        }
        let scale = match scale {
            "layout" => "DimensionScale::Layout",
            "text" => "DimensionScale::Text",
            _ => panic!("dimension `{key}` uses unknown scale `{scale}`"),
        };
        output.push_str(&format!(
            "        DimensionKey::{key} => ({number:?}, {scale}),\n"
        ));
    }
    output.push_str("    }\n}\n\nmacro_rules! dimension {\n");
    for key in dimensions.keys() {
        output.push_str(&format!(
            "    ({key}) => {{ __resource_context!().dimension(crate::resources::DimensionKey::{key}) }};\n"
        ));
    }
    output.push_str("}\n\n");
}

/// Generates image keys and validates placeholder or file-backed resource declarations.
fn generate_image_resources(
    output: &mut String,
    images: &BTreeMap<String, String>,
    resource_root: &Path,
) {
    generate_key_enum(output, "ImageKey", images.keys());
    output.push_str("\n/// Returns the source declaration for a generated image key.\n");
    output.push_str(
        "pub(crate) fn generated_image(key: ImageKey) -> ImageResource {\n    match key {\n",
    );
    for (key, value) in images {
        let expression = if let Some(placeholder) = value.strip_prefix("placeholder:") {
            if placeholder.is_empty() {
                panic!("image `{key}` has an empty placeholder");
            }
            format!("ImageResource::Placeholder({})", rust_string(placeholder))
        } else if let Some(path) = value.strip_prefix("file:") {
            let full_path = resource_root.join(path);
            if !full_path.is_file() {
                panic!(
                    "image `{key}` references missing file {}",
                    full_path.display()
                );
            }
            format!(
                "ImageResource::File {{ path: {}, bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/resources/{path}\")) }}",
                rust_string(path)
            )
        } else {
            panic!("image `{key}` must use placeholder:value or file:relative/path");
        };
        output.push_str(&format!("        ImageKey::{key} => {expression},\n"));
    }
    output.push_str("    }\n}\n\nmacro_rules! image {\n");
    for key in images.keys() {
        output.push_str(&format!(
            "    ({key}) => {{ __resource_context!().image(crate::resources::ImageKey::{key}) }};\n"
        ));
    }
    output.push_str("}\n");
}

/// Emits a lowercase resource-key enum whose variants preserve properties keys exactly.
fn generate_key_enum<'a>(
    output: &mut String,
    enum_name: &str,
    keys: impl Iterator<Item = &'a String>,
) {
    output.push_str("#[allow(non_camel_case_types)]\n");
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    output.push_str(&format!("pub enum {enum_name} {{\n"));
    for key in keys {
        output.push_str(&format!("    {key},\n"));
    }
    output.push_str("}\n");
}

/// Parses a supported hexadecimal or rgba functional color into normalized channels.
fn parse_color(key: &str, value: &str) -> [f32; 4] {
    if let Some(hex) = value.strip_prefix('#') {
        if hex.len() != 6 && hex.len() != 8 {
            panic!("color `{key}` must use #RRGGBB or #RRGGBBAA");
        }
        let channel = |range| {
            u8::from_str_radix(&hex[range], 16)
                .unwrap_or_else(|_| panic!("color `{key}` contains invalid hex digits"))
                as f32
                / 255.0
        };
        return [
            channel(0..2),
            channel(2..4),
            channel(4..6),
            if hex.len() == 8 { channel(6..8) } else { 1.0 },
        ];
    }
    if let Some(arguments) = value
        .strip_prefix("rgba(")
        .and_then(|value| value.strip_suffix(')'))
    {
        let parts = arguments.split(',').map(str::trim).collect::<Vec<_>>();
        if parts.len() != 4 {
            panic!("color `{key}` rgba value must contain four channels");
        }
        let byte = |index: usize| {
            parts[index]
                .parse::<u8>()
                .unwrap_or_else(|_| panic!("color `{key}` has invalid byte channel"))
                as f32
                / 255.0
        };
        let alpha = parts[3]
            .parse::<f32>()
            .unwrap_or_else(|_| panic!("color `{key}` has invalid alpha channel"));
        if !(0.0..=1.0).contains(&alpha) {
            panic!("color `{key}` alpha must be between zero and one");
        }
        return [byte(0), byte(1), byte(2), alpha];
    }
    panic!("color `{key}` must use #RRGGBB, #RRGGBBAA, or rgba(r,g,b,a)");
}

/// Extracts unique named placeholders while preserving their first appearance order.
fn placeholders(template: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut seen = BTreeSet::new();
    let mut rest = template;
    while let Some(start) = rest.find('{') {
        if rest[..start].contains('}') {
            panic!("text template `{template}` has an unmatched closing brace");
        }
        let after_start = &rest[start + 1..];
        let end = after_start
            .find('}')
            .unwrap_or_else(|| panic!("text template `{template}` has an unclosed placeholder"));
        let name = &after_start[..end];
        if name.is_empty()
            || !name
                .chars()
                .all(|character| character.is_ascii_lowercase() || character == '_')
        {
            panic!("text template `{template}` contains invalid placeholder `{{{name}}}`");
        }
        if seen.insert(name.to_owned()) {
            names.push(name.to_owned());
        }
        rest = &after_start[end + 1..];
    }
    if rest.contains('}') {
        panic!("text template `{template}` has an unmatched closing brace");
    }
    names
}

/// Escapes arbitrary properties text as a Rust string literal.
fn rust_string(value: &str) -> String {
    format!("{value:?}")
}
