[package]
name = "bingwall"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
dirs = "6"
iced = { version = "0.14", features = ["advanced", "image", "svg", "tokio"] }
image = "0.25"
regex = "1"
reqwest = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
url = "2"
